Replace bukkit consumer with java consumer
There are really no purpose to use the org.bukkit.util.Consumer class,
since Java 8 comes with the java.util.function.Consumer class.

Also, using the org.bukkit.util.Consumer class gave a NoClassDefFoundError
on MC 1.8, so this fixes it.